id = "arb"
name = "ARB"
description = "Language support for Flutter ARB localization files"
version = "0.0.1"
schema_version = 1
authors = ["Alexander Ravenscroft <alex.ravenscroft.dev@gmail.com>"]
repository = "https://github.com/AlexanderRavenscroft/arb"

[language_servers.arb-language-server]
name = "ARB LSP"
language = "ARB"
language_ids = { "ARB" = "json" }

[grammars.json]
repository = "https://github.com/tree-sitter/tree-sitter-json"
rev = "ee35a6ebefcef0c5c416c0d1ccec7370cfca5a24"
